#Tipos Str -> String -> Texto 12/06/2023

"""
Python = Linguagem de programação
Tipo de tipagem = Dinâmica / Forte
str -> string -> texto
Strings são textos que estão dentro de aspas
"""

# Aspas simples
print('Vinicius Zile')
print(1, 'Vinicius "Zile"')

# Aspas duplas
print("Vinicius Zile")
print(2, "Vinicius 'Zile'")

# Escape
print("Vincius \"Zile\"")

# r
print(r"Vinicius \"Zile\"")