"""
Listas em Python 10/07/2023
Tipo list - Mutável
Suporta vários valores de qualquer tipo
Conhecimentos reutilizáveis - índices e fatiamento
Métodos úteis: append, insert, pop, del, clear, extend, + 
"""


#        0    1      2              3    4
#       -5   -4     -3             -2   -1
lista = [123, True, 'zile',  1.2, []]
lista[-3] = 'Maria'
print(lista)
print(lista[2], type(lista[2]))